# 1 Расчет амортизационных отчислений

**Основной капитал** - материальные активы/имущество предприятия, многократно участвующие в производственном процессе и постепенно переносящие св. стоимость на себестоимость.

*Состоит из*:

- осн. средства. склады, оборудование, тс, инвентарь.
- нематериальные активы. патенты, авторские права.
- финансовые. вложения сроком более 12 мес. инвестиции в виде облигаций.

**Структура основного капитала** - доля каждой составляющей основного капитала в общей совокупности на дату.

**Стоимость основных средств**:

- первоначальная. Вкл. все расходы на приобретение, изготовление и довоедния до эксплуатации.
- остаточная. Учитывают износ. = Sперв. - Sa, где Sa - сумма амортизации.
- ликвидационная. Стоимость в момент списания.
- среднегодовая. Учитывают выбытие(списание) и ввод в эксплуатацию в течение года.
- восстановительная. Делают переоценку первоначальной стоимости в тек. условиях. По ней уже оценивают состояние основных средств, т.к. величина показательна.

**Износ осн. средства** - уменьшение первоначальной стоимости осн. средства в результате деятельности (физический) или научно-технического прогресса (моральный).

---

**Амортизация** - постепенный перенос стоимости собственных *основных средств* на себестоимость продукции с целью дальнейшего их восполнения.

*Способы начисления*:

- *линейная*. Равными долями в течение всего срока полезного использования.

- *уменьшенным остатоком*. Равномерно убывающими долями от макс. в начале срока ПИ до мин. к концу. 
Стоимость основного средства полностью не переносится на себестоимость

- *отдельно для каждоого года*. Равномерно убывающими долями. Отличается от уменьшенного остатка тем, что полностью переносит стоимость осн. средства на себестоимость.

- *пропорционально объему продукции*. Применяют в случае прямой зависимости срока службы осн. средства от частоты его эксплуатации

**Норма амортизации** - установленный процент отчислений в %.

**Сумма амотизации** - стоимостная оценка амортизации в абс. единицах.

Амортизацию относят к себестоимости (РСЭО), эта сумма идет в амортизационный фонд, который исп. для слудующего восполнения основных средств.

Амортизация учитывает износ + уменьшает налоговую базу + является источником восполнения осн. ср-в.

In [1]:
import pandas as pd

data = pd.read_csv('source.csv', delimiter="   ", header=None,
                   engine='python', names=('name', 'value'))
pd.set_option('max_colwidth', None)
data

                                                           name    value
0                     Объем производства и продаж товара 1, шт.     5000
1                     Объем производства и продаж товара 2, шт.     6000
2                     Объем производства и продаж товара 3, шт.    10000
3                            Материальные затраты товар 1, руб.      250
4                            Материальные затраты товар 2, руб.      400
5                            Материальные затраты товар 3, руб.      250
6      Основная заработная плата основных рабочих товар 1, руб.      110
7      Основная заработная плата основных рабочих товар 2, руб.      120
8      Основная заработная плата основных рабочих товар 3, руб.      120
9                   Первоначальная стоимость оборудования, руб.  3000000
10                            Срок полезного использования, лет       10
11                                        Цеховые расходы, руб.   500000
12                                      Заводские расходы, руб.  2300000
13                                     Затраты на рекламу, руб.   300000
14                   Доходы от прочей деятельности за год, руб.   500000
15                  Расходы от прочей деятельности за год, руб.   700000
16           Длительность производственного цикла товара 1, дни       20
17           Длительность производственного цикла товара 2, дни       25
18          Длительность производственного цикла  товара 3, дни       29
19     Время хранения готовой продукции на складе товара 1, дни       14
20     Время хранения готовой продукции на складе товара 2, дни       12
21     Время хранения готовой продукции на складе товара 3, дни       14
22                                          Цена товара 1, руб.      600
23                                          Цена товара 2, руб.      700
24                                          Цена товара 3, руб.      680
25         Интервал между поставками материала по товару 1, дни       15
26         Интервал между поставками материала по товару 2, дни       20
27         Интервал между поставками материала по товару 3, дни       30
28  Страховой запас, % от текущего запаса (для всех материалов)       20

необходимо рассчитать величину амортизационных отчислений линейным способом (рассчитать норму и сумму амортизации за год)

In [2]:
na = (data['value'][9] - 0) / (data['value'][9] * data['value'][10])
sa = data['value'][9] * na
print('Норма амортизации за год:', na*100)
print('Сумма амортизации за год', sa)

Норма амортизации за год: 10.0
Сумма амортизации за год 300000.0

В данном разделе курсовой работы необходимо рассчитать порог рентабельности, запас финансовой прочности в рублях и в процентах, операционный рычаг (все показатели считаются по предприятию в целом).

# 2 Расчет себестоимости единицы продукции

**Себестоимость** - стоимостная оценка затрат (ресурсов: осн. средства, трудовые ресурсы, топливо, материал) на производство и *реальзицию товаров*/услуг (продажу).

**Группиовки затрат**:

1. **Смета затрат за период**

- материальные. сырье и проч.
- зп и премии
- страховые взносы
- амотизационные отчисления
- прочие расходы

На ее основе определяют себестоимость единицы продукции (полн. с / объем продукции), если продуция однородная.

Определяют и **структуру затрат** - удельный вес каждой составляющей затрат в общем отношении за период.

Анализ структуры затрат необходим для снижения себестоимости.

2. **Калькуляция** - расчет себестоимости единицы продукции в денежном выражении.

На ее основе определяют себестоимость единицы продукции.

**Осн. статьи калькуляции** (производственное предприятие):

- цеховая себестоимость, т.е. затраты подразделения: 
  1. осн. зп осн. рабочих
  2. доп. зп осн. рабочих
  3. отчисления с зп осн. рабочих
  4. топливо
  5. расходы на содержание и эксплуатацию оборудования (РСЭО)
  6. осн. материалы
  7. вспомогат. материалы
  8. полуфабрикаты
  9. расходы на освоение производства
  10. общепроизводственные расходы
- производственная себестоимость: цеховая себестоимость + 
  11. общехоз. расходы
  12. брак
  13. проч. производственные расходы.
- *Полная себестоимость*: производственная себестоимость + 
  14. внепроизводственные расходы.

**Осн. статьи калькуляции** (предприятие сферы услуг):

- полуфабрикаты
- *сдельная зп* - сколько выполнил, столько и получил.
- соц. отчисления с сдельной зп
- *накладные расходы* (аренда, реклама, маркетинг, комунальые услуги, ремонт основных средств)

**Осн. статьи калькуляции** (торгового предприятие):

- товары для перепродажи
- полуфабрикаты
- премии к зп
- накладные расходы

Виды затрат по способу отнесения на себестоимость:

1. прямые. связаны с производственным процессом или оказанием услуги, т.е. их можно напрямую отнести к опр. товару, т.к. напряму связаны с его созданием. (зп осн рабочих, полуфабрикаты)
2. косвенные. не относятся напрямую к производству продукции, но связаны с производствам. (зп менеджера, комуналка, налоги, реклама).

Алгоритм расчета косвенных затрат зависит от способа распределения. Для производственного предприятия способы распределения: пропорционально осн. зп осн. рабочих, прямым затратам и заводской себестоимости. Для торгововго предприятия: прямым затратам, доле выручки каждого товара в общ. объеме выручки. Для сферы услуг: также как и торгового.

Выбирается признак (относительно чего: осн. зп. осн. рабочих) и категория затрат (внепроизводственные затраты) и считается коэф. косвенных расходов.

In [3]:
import numpy as np
plain_expenses = pd.DataFrame({
    'Статьи прямых затрат': ['Материальные затраты, руб.', 'Основная заработная плата основных рабочих, руб.', 'Страховые взносы (на основную заработную плату основных рабочих), руб.'],
    'Товар 1': [np.NaN]*3,
    'Товар 2': [np.NaN]*3,
    'Товар 3': [np.NaN]*3},
    columns = ['Статьи прямых затрат', 'Товар 1', 'Товар 2', 'Товар 3'])

# add initial data to dataframe
plain_expenses.iloc[0, 1:] = data.iloc[3:6].value
plain_expenses.iloc[1, 1:] = data.iloc[6:9].value

# подсчет страховых взносов
a = plain_expenses.iloc[1, 1] * 0.3
c = plain_expenses.iloc[1, 2] * 0.3
b = plain_expenses.iloc[1, 3] * 0.3
plain_expenses.iloc[2, 1:] = a, b, c

plain_expenses

,Статьи прямых затрат,Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.0,400.0,250.0
1,"Основная заработная плата основных рабочих, руб.",110.0,120.0,120.0
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.0,36.0,36.0

In [4]:
from operator import mul

indir_expenses = np.array([['Расходы на содержание и эксплуатацию оборудования (РСЭО)', np.NaN],
         ['Цеховые расходы', np.NaN],
         ['Заводские расходы', np.NaN],
         ['Внепроизводственные расходы', np.NaN],
         ['Итого косвенные затраты', np.NaN]])
indir_expenses = pd.DataFrame(indir_expenses, columns=('Статьи косвенных затрат', 'Сумма за год, руб.'))

# add initial data
indir_expenses.iloc[1:3, 1]  = data.iloc[11:13].value
indir_expenses.iloc[0, 1] = sa  # РСЭО = сумме амортизации
indir_expenses.iloc[3, 1] = data.value[13]  # внепроизв. расходы = расходы на рекламу
indir_expenses.loc[4, ['Сумма за год, руб.']] = indir_expenses.iloc[:4, 1].sum()

indir_expenses

                                    Статьи косвенных затрат Сумма за год, руб.
0  Расходы на содержание и эксплуатацию оборудования (РСЭО)           300000.0
1                                           Цеховые расходы             500000
2                                         Заводские расходы            2300000
3                               Внепроизводственные расходы             300000
4                                   Итого косвенные затраты          3400000.0

зп осн. рабочих за год, сдельная (объем товара * себестоимость затрат на товар)

Аналогично для материальных затрат  и страховых

Полуаем общ. прямые затраты

In [5]:
cost_volume = data.iloc[0:3].value
year_salary = sum(map(lambda tpl: mul(*tpl), zip(plain_expenses.iloc[1, 1:].values, cost_volume)))
mater_expenses = sum(map(lambda tpl: mul(*tpl), zip(plain_expenses.iloc[0, 1:].values, cost_volume)))
strah_expenses = sum(map(lambda tpl: mul(*tpl), zip(plain_expenses.iloc[2, 1:].values, cost_volume)))
total_plain_cost = year_salary + mater_expenses + strah_expenses
total_plain_cost

9361000.0

1. Расходы на содержание и эксплуатацию оборудования распределяются пропорционально основной заработной плате основных рабочих (сдельной заработной плате).
2. Цеховые и заводские расходы распределяются пропорционально прямым затратам.
3. Внепроизводственные расходы распределяются пропорционально заводской себестоимости.

Считаю коэффы

In [6]:
# на 1 рубль основной зп осн. рабочих приходится 12 копеек расходов на СЭО
k1 = indir_expenses.iloc[0, 1] / year_salary
# на 1 рубль прямых затрат приходится 8 копеек цеховых затрат
k2_ceh = indir_expenses.iloc[1, 1] / total_plain_cost
# На 1 рубль прямых затрат приходится 37 копейки заводских затрат
k2_prod = indir_expenses.iloc[2, 1] / total_plain_cost
k1, k2_ceh, k2_prod

(0.1214574898785425, 0.05341309689135776, 0.2457002457002457)

In [7]:
# df1 с прямыми и косвенными видами затрат на кажый товар
part_1 =indir_expenses.iloc[:-2, 0]
part_2 = plain_expenses.iloc[:, 0]
part_3 = np.concatenate((part_1[:-1], ['Цеховая себестоимость'], [part_1[2]], ['Заводская себестоимость']))
df1 = pd.DataFrame({'Статья затрат, руб.': np.concatenate((part_2, part_3))})
for k, v in {i: [np.NaN]*df1.shape[0] for i in plain_expenses.columns[1:]}.items():
    df1[k] = v
df1.iloc[:3, 1:] = plain_expenses.iloc[:, 1:]
df1

,"Статья затрат, руб.",Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.0,400.0,250.0
1,"Основная заработная плата основных рабочих, руб.",110.0,120.0,120.0
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.0,36.0,36.0
3,Расходы на содержание и эксплуатацию оборудования (РСЭО),NaN,NaN,NaN
4,Цеховые расходы,NaN,NaN,NaN
5,Цеховая себестоимость,NaN,NaN,NaN
6,Заводские расходы,NaN,NaN,NaN
7,Заводская себестоимость,NaN,NaN,NaN

In [8]:
# for i in df1.columns[1:]:
#     df1[i][3] = round(k1 * df1[i][1], 2)
# df1
for good in df1.columns[1:]:
    df1.loc[3, [good]] = k1 * df1.loc[1, [good]]  # РСЭО = коэф * зп по каждому товару
    df1.loc[4, [good]] = k2_ceh * sum(plain_expenses[good])  # Цеховые расходы = коэф * сумма прямых затрат по товару
    df1.loc[5, [good]] = sum(df1.loc[:4, [good]][good])  # Цеховaя себестоимость = сумма 0-4
    df1.loc[6, [good]] = k2_prod * sum(plain_expenses[good])  # заводские расходы = коэф * сумма прямых затрат по товару
    df1.loc[7, [good]] = df1.loc[5, [good]] + df1.loc[6, [good]]  # заводская себестоимость = цеховая + заводские расходы
    df1[good] = df1[good].round(2)

df1

,"Статья затрат, руб.",Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.00,400.00,250.00
1,"Основная заработная плата основных рабочих, руб.",110.00,120.00,120.00
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.00,36.00,36.00
3,Расходы на содержание и эксплуатацию оборудования (РСЭО),13.36,14.57,14.57
4,Цеховые расходы,20.99,29.70,21.69
5,Цеховая себестоимость,427.35,600.27,442.26
6,Заводские расходы,96.56,136.61,99.75
7,Заводская себестоимость,523.91,736.88,542.01

In [9]:
# считаю общ. заводскую себестоимость и определяю коэф коммерческих расходов
prod_expenses = sum(map(lambda tpl: mul(*tpl), zip(df1.iloc[7, 1:].values, cost_volume)))
# на 1 рубль производственной себестоимости приходится 2 копеек коммерческих затрат
k_commerce = indir_expenses.iloc[3, 1] / prod_expenses
prod_expenses, k_commerce

(12460930.0, 0.024075249600150228)

In [60]:
data

                                                           name    value
0                     Объем производства и продаж товара 1, шт.     5000
1                     Объем производства и продаж товара 2, шт.     6000
2                     Объем производства и продаж товара 3, шт.    10000
3                            Материальные затраты товар 1, руб.      250
4                            Материальные затраты товар 2, руб.      400
5                            Материальные затраты товар 3, руб.      250
6      Основная заработная плата основных рабочих товар 1, руб.      110
7      Основная заработная плата основных рабочих товар 2, руб.      120
8      Основная заработная плата основных рабочих товар 3, руб.      120
9                   Первоначальная стоимость оборудования, руб.  3000000
10                            Срок полезного использования, лет       10
11                                        Цеховые расходы, руб.   500000
12                                      Заводские расходы, руб.  2300000
13                                     Затраты на рекламу, руб.   300000
14                   Доходы от прочей деятельности за год, руб.   500000
15                  Расходы от прочей деятельности за год, руб.   700000
16           Длительность производственного цикла товара 1, дни       20
17           Длительность производственного цикла товара 2, дни       25
18          Длительность производственного цикла  товара 3, дни       29
19     Время хранения готовой продукции на складе товара 1, дни       14
20     Время хранения готовой продукции на складе товара 2, дни       12
21     Время хранения готовой продукции на складе товара 3, дни       14
22                                          Цена товара 1, руб.      600
23                                          Цена товара 2, руб.      700
24                                          Цена товара 3, руб.      680
25         Интервал между поставками материала по товару 1, дни       15
26         Интервал между поставками материала по товару 2, дни       20
27         Интервал между поставками материала по товару 3, дни       30
28  Страховой запас, % от текущего запаса (для всех материалов)       20

In [10]:
# заношу в массив сумму коммерческих расходов и полной себестоимсости на единицу продукцции (т.е. товара)
commerce_expenses = (round(df1.loc[7, [good]][good] * k_commerce, 2) for good in df1.columns[1:])
df1.loc[len(df1)] = ['Внепроизводственные расходы', *commerce_expenses]
total_expenses = (df1.loc[7, [good]][good] + df1.loc[8, [good]][good] 
                  for good in df1.columns[1:])
df1.loc[len(df1)] = ['Полная себестоимость единицы продукции (ATC)', *total_expenses]
df1

,"Статья затрат, руб.",Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.00,400.00,250.00
1,"Основная заработная плата основных рабочих, руб.",110.00,120.00,120.00
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.00,36.00,36.00
3,Расходы на содержание и эксплуатацию оборудования (РСЭО),13.36,14.57,14.57
4,Цеховые расходы,20.99,29.70,21.69
5,Цеховая себестоимость,427.35,600.27,442.26
6,Заводские расходы,96.56,136.61,99.75
7,Заводская себестоимость,523.91,736.88,542.01
8,Внепроизводственные расходы,12.61,17.74,13.05
9,Полная себестоимость единицы продукции (ATC),536.52,754.62,555.06

# 3 Расчет нормируемого оборотного капитала

**Оборотный капитал** - активы, однократно участвующее в производственном процессе, полностью преносит св. стоимость на себестоимость продукции, восполняется в конце производственного цикла.

*Состоит из*:

- запасы. всего: готовой продукцции, сырья, полуфабрикатов, незаверш. продукции.
- дебиторская задолженность (дз). то что тебе должны.
- деньги в кассе и на балансе
- финанс. вложения сроком менее 12 месяцев

**Структура оборотного капитала** - удельный вес каждой составляющей об. кап в общем отношении в относительных величинах на дату.

*Структура об. кап. расчитвыается после группировки на*:

- материальные активы. все что существует по факту, все выше перечисленное кроме дз.
- по риску. мин. риск; малый риск; ср. риск; высокий риск
- по ликвидности
  1. ликвидные. дс, фин. вложения.
  2. ср. ликвидные. дз.
  3. неликидные. запасы.
- по сфере обращения
  - касаемо производства (запас сырья и т.д.)
  - касаемо непроизводства (готовая продукция, дз, дс, отгруж. товар)
- по особенностям контроля
  - нормируемые. простые запасы
  - ненормируемые. дз, отгруженный товар, денежные средства
- по формированию
  - собственные
  - заемные
  
Для оценки платежеспособности предприятия исп. **коэффы ликвидности**:

- К абс. ликв.
- К промежут. ликв.
- К тек. ликв.

*Стадии об. капитала*: ДC -> Т -> П -> T' -> ДC' (производственное предприятие). ДС -> Т -> ДC' (торговое).

Показатели **оборачиваемости** (на сколько эффективно исп. об. ср-ва за период):

- Скорость оборота/коэф. оборачиваемости. число оборотов за период.
- Длительность оборота.
- Коэф. загрузки об. ср-в. сколько об. ср-в нужно для получения 1 руб. выручки.
- рентабельность. n% с ПРдоН получает предприятие с 1 руб, влоденного в об. капитал.

**Нормирование об. капитала** - определение мин. величины об. ср-в для работы, т.е. **нормы** (в относит. величинах) или **норматива** (в абс. величинах). Т.е. задача нацти нормируемый об. капитал, его мин. значение. $Sнобк = Sз + Sнзп + Sгп$

норматив об. средств в виде запасов (Sз) общ в руб

In [11]:
# среднедневное потребление каждого вида сырья = потребность (объем * мат. затраты) / 365
qc1 = (data.loc[3, 'value'] * data.loc[0, 'value']) / 365
qc2 = (data.loc[4, 'value'] * data.loc[1, 'value']) / 365
qc3 = (data.loc[5, 'value'] * data.loc[2, 'value']) / 365

# норматив запаса в днях = тек. запас + страх. запас
t1_now = 0.5 * data.loc[25, 'value']  # тек. запас = 0.5 * интервал поставок или 0.5*(интервал+доп веремя на приемку)
t2_now = 0.5 * data.loc[26, 'value']
t3_now = 0.5 * data.loc[27, 'value']

t1_strah = t1_now * 0.2  # страх запас = тек. запас *  выбранный процент
t2_strah = t2_now * 0.2
t3_strah = t3_now * 0.2

# норматив запасов в днях, формула выше
t_nz_1 = t1_now + t1_strah
t_nz_2 = t2_now + t2_strah
t_nz_3 = t3_now + t3_strah

# норматив запасов общ. в руб
sz_1 = t_nz_1 * qc1
sz_2 = t_nz_2 * qc2
sz_3 = t_nz_3 * qc3

sz_common = sz_1 + sz_2 +sz_3
sz_common

233013.698630137

норматив об. средств в нез. производстве общ в руб (Sнзп)

считают если период товарооборота больше 24 часов.

In [12]:
# среднеднесной выпуск продукции по полной себестоимости в руб = (полн. с товара * объем) / 365
q1_seb = (df1.loc[9, 'Товар 1'] * data.loc[0, 'value']) / 365  
q2_seb = (df1.loc[9, 'Товар 2'] * data.loc[0, 'value']) / 365
q3_seb = (df1.loc[9, 'Товар 3'] * data.loc[0, 'value']) / 365

# коэф нараст. затрат, показывающий степень готовности изделия = 
# (общ среднеднев. потрбление сырья / среднеднев. выпуск продукции) как A + ((1 - A) / 2)
A1 = q1_seb / qc1
A2 = q2_seb / qc2
A3 = q3_seb / qc3
k1_nz = A1 + ((1 - A1) / 2)
k2_nz = A2 + ((1 - A2) / 2)
k3_nz = A3 + ((1 - A3) / 2)

# норматив об. ср-в в нез. производстве общ в руб = коэф нараст затрат * среднеднев. выпуск продукц + длит. цикла
s_nzp1 = q1_seb * k1_nz * data.loc[16, 'value']
s_nzp2 = q2_seb * k2_nz * data.loc[17, 'value']
s_nzp3 = q3_seb * k3_nz * data.loc[18, 'value']

s_nzp_common = s_nzp1 + s_nzp2 + s_nzp3
s_nzp_common

796227.2193719177

норматив об. ср-в гоотовой продукции Sгп в руб

In [13]:
# норматив готов продукц = среднеднев выпуск по полн себ * длит хранения на складе
s_gp1 = q1_seb * data.loc[19, 'value']
s_gp2 = q2_seb * data.loc[20, 'value']
s_gp3 = q3_seb * data.loc[21, 'value']
s_gp_common = s_gp1 + s_gp2 + s_gp3
s_gp_common

333391.2328767123

Нормируемый об. капитал

In [14]:
norm_ob_capital = sz_common + s_nzp_common + s_gp_common
norm_ob_capital

1362632.150878767

# 4 Расчет прибыли и рентабельности

**выручка от реализации** = цена продажи за единицу * объем продаж в шт

**прибыль от продаж** = выручка от продаж - полн. с (только основная деятельность)

**прибыль до налогообложения** = прибыль от продаж + прочие доходы - прочие расходы (основная и прочая деятельность)

**чистая прибыль** = прибыль до налогообложения * налог на прибыль (остается в собственности, в случае АО идет на дивиденды, фонды и т.д.)

**рентабельность** - относительный показатель эффективности работы предприятия за период.

- продаж = прибыль от продаж / выручка от продаж. n руб. прибыли от продаж содержится в 1 руб выручки
- затрат = прибыль от продаж / полн. с. n руб. прибыли от продаж приходится на 1 руб полной себестоимости
- *активов* = ПрдоН / средняя стоимость активов (все имущество в собственности: осн. и об. капиталы) n% прибыли до налогообложения получает предприятие с 1 руб, вложенного в активы.
- основного и оборотного капитала. как активов только береться ср. стоимость каждого из видов активов отдельно. n% прибыли до налогообложения получает предприятия с 1 руб, вложенного в вид капитала.

In [ ]:
годовая выручка Vp = Qn * Pn, руб

In [15]:
# revenue1 = data.loc[0, 'value'] * data.loc[22, 'value']
# revenue2 = data.loc[1, 'value'] * data.loc[23, 'value']
# revenue3 = data.loc[2, 'value'] * data.loc[24, 'value']
# revenue_year = sum((revenue1, revenue2, revenue3))
revenue_year = sum(map(lambda tpl: mul(*tpl), zip(data.iloc[22:25, 1], data.iloc[:3, 1])))
revenue_year

14000000

полн. с, руб.

In [16]:
full_expenses_year = sum(map(lambda tpl: mul(*tpl), zip(df1.iloc[9, 1:], cost_volume)))
full_expenses_year

12760920.0

годовая прибыль от продаж за год. ПР = выручка - полн. с

In [17]:
profit_year = revenue_year - full_expenses_year
profit_year

1239080.0

прибль до налогооблажения 20 % за год. ПРдоН = ПР + ПрД - ПрР

In [18]:
profit_before_tax = profit_year + data.loc[14, 'value'] - data.loc[15, 'value']
profit_before_tax

1039080.0

Чистая прибыль за год. ЧП = ПрдоН - налог на прибыль (20%)

In [19]:
clear_profit = profit_before_tax + profit_before_tax * 0.2  # + т.к. отрицательна ПРдоН
clear_profit

1246896.0

Рентабильность продаж и затрат

In [20]:
# продаж = ПР / выручка * 100%
sale_efficiency = profit_year / revenue_year * 100
# затрат = ПР / полн с * 100%
expenses_efficiency = profit_year / full_expenses_year * 100

sale_efficiency, expenses_efficiency

(8.850571428571428, 9.709958216178771)

In [21]:
df2 = pd.DataFrame({
    'Показатель': ('выручка, руб', 'полн. с, руб.', 'ПР, руб.', 'ПРдоН, руб.', 'ЧП, руб.', 
                                 'Рентабильность продаж, %', 'Рентабильность затрат, %'),
    'Значение': map(lambda x: round(x, 2), (revenue_year, full_expenses_year, profit_year, profit_before_tax, clear_profit,
                 sale_efficiency, expenses_efficiency))},

)
df2

                 Показатель     Значение
0              выручка, руб  14000000.00
1             полн. с, руб.  12760920.00
2                  ПР, руб.   1239080.00
3               ПРдоН, руб.   1039080.00
4                  ЧП, руб.   1246896.00
5  Рентабильность продаж, %         8.85
6  Рентабильность затрат, %         9.71

# 5 Расчет показателей эффективности использования основного и оборотного капитала

**Показатели эффективности**:
- капиталоотдача
- капиталоемкость
- рентабельность осн. капитала

---
(оборачиваемости)
- коэф. оборачиваемости об. ср-в
- длительность одного оборота
- коэф. загрузки об. ср-в
- рентабельность об. капитала

In [22]:
# остаточная стоимотсь осн. ср-в на конец года = перв. стоимость оборудования - сумма амортизации.
# т.е. стоимость осн. ср-в на конец года
left_main_assets = data.loc[9, 'value'] - sa

# cр. стоимость осн. ср-в = (НГ + КГ) / 2
average_main_assets = (data.loc[9, 'value'] + left_main_assets) * 0.5
average_main_assets

2850000.0

капиталоотдача = выручка или обхем продаж / ср. стоимость осн. ср-в

In [23]:
ko = revenue_year / average_main_assets
ko

4.912280701754386

капиталоемкость = 1 / капитолоотдача

In [24]:
kb = 1 / ko
kb

0.20357142857142857

рентабельность осн. капитала = ПРдоН/ср. стоимость осн. капитала

In [25]:
main_assests_efficiency = profit_before_tax / average_main_assets * 100
main_assests_efficiency

36.45894736842105

коэф. оборачиваемости об. ср-в (скорость оборота) = выручка / ср. стоимость об. капитала

In [53]:
data

                                                           name    value
0                     Объем производства и продаж товара 1, шт.     5000
1                     Объем производства и продаж товара 2, шт.     6000
2                     Объем производства и продаж товара 3, шт.    10000
3                            Материальные затраты товар 1, руб.      250
4                            Материальные затраты товар 2, руб.      400
5                            Материальные затраты товар 3, руб.      250
6      Основная заработная плата основных рабочих товар 1, руб.      110
7      Основная заработная плата основных рабочих товар 2, руб.      120
8      Основная заработная плата основных рабочих товар 3, руб.      120
9                   Первоначальная стоимость оборудования, руб.  3000000
10                            Срок полезного использования, лет       10
11                                        Цеховые расходы, руб.   500000
12                                      Заводские расходы, руб.  2300000
13                                     Затраты на рекламу, руб.   300000
14                   Доходы от прочей деятельности за год, руб.   500000
15                  Расходы от прочей деятельности за год, руб.   700000
16           Длительность производственного цикла товара 1, дни       20
17           Длительность производственного цикла товара 2, дни       25
18          Длительность производственного цикла  товара 3, дни       29
19     Время хранения готовой продукции на складе товара 1, дни       14
20     Время хранения готовой продукции на складе товара 2, дни       12
21     Время хранения готовой продукции на складе товара 3, дни       14
22                                          Цена товара 1, руб.      600
23                                          Цена товара 2, руб.      700
24                                          Цена товара 3, руб.      680
25         Интервал между поставками материала по товару 1, дни       15
26         Интервал между поставками материала по товару 2, дни       20
27         Интервал между поставками материала по товару 3, дни       30
28  Страховой запас, % от текущего запаса (для всех материалов)       20

In [52]:
df1

,"Статья затрат, руб.",Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.00,400.00,250.00
1,"Основная заработная плата основных рабочих, руб.",110.00,120.00,120.00
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.00,36.00,36.00
3,Расходы на содержание и эксплуатацию оборудования (РСЭО),13.36,14.57,14.57
4,Цеховые расходы,31.95,45.20,33.01
5,Цеховая себестоимость,438.31,615.78,453.58
6,Заводские расходы,146.98,207.93,151.84
7,Заводская себестоимость,585.29,823.71,605.42
8,Внепроизводственные расходы,12.61,17.75,13.05
9,Полная себестоимость единицы продукции (ATC),597.90,841.46,618.47

,"Статья затрат, руб.",Товар 1,Товар 2,Товар 3
0,"Материальные затраты, руб.",250.00,400.00,250.00
1,"Основная заработная плата основных рабочих, руб.",110.00,120.00,120.00
2,"Страховые взносы (на основную заработную плату основных рабочих), руб.",33.00,36.00,36.00
3,Расходы на содержание и эксплуатацию оборудования (РСЭО),13.36,14.57,14.57
4,Цеховые расходы,31.95,45.20,33.01
5,Цеховая себестоимость,438.31,615.78,453.58
6,Заводские расходы,146.98,207.93,151.84
7,Заводская себестоимость,585.29,823.71,605.42
8,Внепроизводственные расходы,12.61,17.75,13.05
9,Полная себестоимость единицы продукции (ATC),597.90,841.46,618.47

In [26]:
kob = revenue_year / norm_ob_capital  # исп. нормир. об. капитал
kob

10.274232844844695

длительность одного оборота = 365 / коэф оборачиваемости

In [27]:
one_ob_time = 365 / kob
one_ob_time

35.525766790767854

коэф. загрузки об. ср-в = 1 / коэф оборачиваемости

In [28]:
kzagr = 1 / kob
kzagr

0.09733086791991193

рентабельность об. капитала

In [29]:
ob_assets_efficiency = profit_before_tax / norm_ob_capital * 100
ob_assets_efficiency

76.25535617443732

In [30]:
df3 = pd.DataFrame({
    'name': ('капиталоотдача', 'капиталоемкость', 'рентабельность осн. капитала',
            'коэфф оборачиваемости', 'длительность одного оборота, день', 'коэфф загрузки',
            'рентабельность об. капитала'),
    'value': (ko, kb, main_assests_efficiency, kob, one_ob_time, kzagr, ob_assets_efficiency)}
)

additional_indicators = pd.DataFrame([('рентабельность продаж', sale_efficiency),
                                    ('рентабельность затрат', expenses_efficiency)])

df4 = pd.DataFrame(np.concatenate((df3.loc[:5], additional_indicators, df3.loc[6:])), columns=df3.columns)
df4.value = df4.value.astype(float)
df4.value = df4.value.round(2)

df4['интерпретация'] = (
    '1 руб. вложенный в основной капитал приносит 4 руб. 91 копейку выручки',
    '20 копеек необходимо влодить в осн. капитал для получения 1 руб. выручки',
    '-14.84% прибыли до налогооблажения получает предприятия с 1 руб, вложенного в осн. капитал',
    '1 руб. вложенный в оборотный капитал приносит 9.01 рублей выручки',
    'длительность 1 оборота об. капитала составляет 40.51 дней',
    '11 копеек необходимо вложить в об. капитал для получения 1 рубля выручки',
    '-1.59 руб прибыли от продаж содержится в 1 руб. выручки',
    '-1.57 руб прибыли от продаж приходится 1 руб полной себестоимости',
    '-27.22% прибыли до налогооблажения получает предприятия с 1 руб, вложенного в об. капитал'
)
df4

,name,value,интерпретация
0,капиталоотдача,4.91,1 руб. вложенный в основной капитал приносит 4 руб. 91 копейку выручки
1,капиталоемкость,0.20,20 копеек необходимо влодить в осн. капитал для получения 1 руб. выручки
2,рентабельность осн. капитала,36.46,"-14.84% прибыли до налогооблажения получает предприятия с 1 руб, вложенного в осн. капитал"
3,коэфф оборачиваемости,10.27,1 руб. вложенный в оборотный капитал приносит 9.01 рублей выручки
4,"длительность одного оборота, день",35.53,длительность 1 оборота об. капитала составляет 40.51 дней
5,коэфф загрузки,0.10,11 копеек необходимо вложить в об. капитал для получения 1 рубля выручки
6,рентабельность продаж,8.85,-1.59 руб прибыли от продаж содержится в 1 руб. выручки
7,рентабельность затрат,9.71,-1.57 руб прибыли от продаж приходится 1 руб полной себестоимости
8,рентабельность об. капитала,76.26,"-27.22% прибыли до налогооблажения получает предприятия с 1 руб, вложенного в об. капитал"

# 6 Расчет точки безубыточности, порога рентабельности, запаса финансовой прочности


*Затраты в зависимости от объемов производства делят*:

- постоянные fixed cost. все в пределах установленной мощности не зависимо от объемов производства, мощность может измениться (новый цех появиться), тогда изменяются, но все равно считаются постоянными.
  - комуналка
  - оклад и страховые взносы на него
  - амортизация линейным способом
- непостоянные variable cost. зависят от объема производства.
  - сдельная зп и страховые наисления на сдельную зп
  - материальные затраты (полуфабрикаты, топливо)

*total cost* = fixed + variable

*average fixed costs* - удельные постоянные, т.е. на единицу продукции.

*average variable cost* - удельные переменные, т.е. на единицу продукции.

*average total cost* - удельные общ, т.е. общ затраты на единицу.

ATC = TC / Q, где Q - обем продукции. Аналогично для AVC и AFC, но со св. значением.

---

**Показатели бузубыточности**:

- точка безубыточности - значение объема производства и продаж, когда прибыль от продаж равна 0. В шт.

- порог рентабельности - стоимостная точка бузубыточности в руб.

- запас финансовой прочности - как далеко предприятие ушло от порога рентабельности. в руб. т.е. на эту величину предприятие может снизить выручку, попадая в порог рентабельности. Счиается в абс. и относит. величинах.

- операционный рычаг - показывает, во сколько раз изменится прибыль при изменении выручки на 1 %.

**Маржинальный доход/маржа** = выручка от продаж - переменные затраты. Сумма остается у компании после вычита затрат. 

На единицу продукции маржа = цена - avc

Коэф. маржи - доля маржи в общ. выручке = маржа / выручка

Деление затрат на постоянные и переменные

In [31]:
df5 = pd.DataFrame({
    'Сумма за год, руб.': (np.NaN for _ in range(7)),
    'Вид затрат': ('fixed', 'variable', 'fixed', 
                   'fixed', 'fixed', 'variable', 'variable')},
    index=('Амортизационные отчисления (РСЭО)',
            'Материальные затраты',
            'Цеховые расходы',
            'Заводские расходы',
            'Затраты на рекламу',
            'Сдельная заработная плата',
            'Страховые взносы на сдельную заработную плату'),
)
df5.index.name = 'Статьи затрат'
df5['Сумма за год, руб.'] = (sa, mater_expenses, 
                                 indir_expenses.iloc[1, 1], indir_expenses.iloc[2, 1],
                                 indir_expenses.iloc[3, 1], year_salary, strah_expenses)
df5

                                               Сумма за год, руб. Вид затрат
Статьи затрат
Амортизационные отчисления (РСЭО)                        300000.0      fixed
Материальные затраты                                    6150000.0   variable
Цеховые расходы                                          500000.0      fixed
Заводские расходы                                       2300000.0      fixed
Затраты на рекламу                                       300000.0      fixed
Сдельная заработная плата                               2470000.0   variable
Страховые взносы на сдельную заработную плату            741000.0   variable

В данном разделе курсовой работы необходимо рассчитать порог рентабельности, запас финансовой прочности в рублях и в процентах, операционный рычаг (все показатели считаются по предприятию в целом).

In [32]:
# совокуп. пост. затарты за год
fc = df5[df5['Вид затрат'] == 'fixed']['Сумма за год, руб.'].sum()
# совокуп. переменные затраты за год
vc = df5[df5['Вид затрат'] == 'variable']['Сумма за год, руб.'].sum()

# совокупные затраты предприятия total cost
tc = fc + vc

# точка бузубыточкности = FC / P - AVC
# ПР = 0, Q = TC = выручка.
# upper_dot = fc / ()

# порог рентабельности = FC / коэф маржи, коэф маржи = маржа / выручка, маржа = выручка - VC
margin = revenue_year - fc
k_margin = margin / revenue_year
efficiency_frame = fc / k_margin
efficiency_frame

4490566.03773585

In [35]:
full_expenses_year, tc

(12760920.0, 12761000.0)

В данном разделе курсовой работы необходимо рассчитать порог рентабельности, запас финансовой прочности в рублях и в процентах, операционный рычаг (все показатели считаются по предприятию в целом).